#!/usr/bin/env node

"use strict";

var app = require('express')(),
    express = require('express'),
    server = require('http').createServer(app),
    io = require('socket.io').listen(server),
    fs = require('fs'),
    when = require('when'),
    sequence = require('sequence'),
    globalSockets = {},
    commander = require('commander');

commander
	.version('0.0.1')
	.option('start', 'start a livectl server')
	.option('connect [address]', 'connect to a livectl server')
	.parse(process.argv);

if (commander.start) {
	console.log('starting server');
}
else if (typeof commander.connect === 'string') {
	console.log('connecting to ' + commander.connect);
}
else {
	commander.outputHelp();
}


